version: "3.9"
services:
  bitcoind:
    image: junderw/bitcoinjs-regtest-server
    ports:
      - 8080:8080
      - 8332:8332
      - 18443:18443
      - 30001:30001
    volumes:
      - ./docker/datadir:/root/.bitcoin
  electrs:
    build: ./docker/electrs
    ports:
      - 3000:3000
    volumes:
      - ./docker/datadir:/data/.bitcoin:ro
      - ./docker/electrs/data:/data/db
    depends_on:
      - bitcoind
    command:
      [
        "-vvvv",
        "--network", "regtest",
        "--db-dir", "/data/db",
        "--daemon-rpc-addr", "bitcoind:18443",
        "--http-addr", "electrs:3000",
        "--cors", "*"
      ]
  esplora:
    build: ./docker/esplora
    ports:
      - 3333:8080
    depends_on:
      - bitcoind
      - electrs