version: "3.9"
services:
  node:
    build: ./regtest-server
    ports:
      - 8080:8080
      - 18443:18443
      - 30001:30001
      - 8333:8333
      - 8332:8332
  electrumx:
    image: lukechilds/electrumx:latest
    depends_on:
      - node
    ports:
      - "51001:50001"
      - "51002:50002"
    environment:
      - NET=regtest
      - COIN=BitcoinSegwit
      - DAEMON_URL=http://terra:hash@node:18443
  explorer:
    image: ulamlabs/btc-rpc-explorer:latest
    depends_on:
      - node
      - electrumx
    ports:
      - "3002:3002"
    environment:
      - BTCEXP_HOST=0.0.0.0
      - BTCEXP_BITCOIND_URI=http://terra:hash@node:18443
      - BTCEXP_ELECTRUMX_SERVERS=tls://electrumx:50002
      - BTCEXP_ADDRESS_API=electrumx