FROM lncm/bitcoind:v22.0

# USER root

# RUN apk update && apk add bash

# USER bitcoind

# COPY --chown=bitcoind:bitcoind start.sh ./

# RUN chmod +x start.sh

# ENTRYPOINT ["./start.sh"]

ENTRYPOINT ["bitcoind"]